### ISSUE TITLE
Error starting 'WiredPlayers'

### ISSUE THREAD

**Issue by randomprogrammer101** [xabier1989/WiredPlayers-RP#18]
Hello

When I wants to start the server after loading everything it's write this for me:
![error](https://user-images.githubusercontent.com/44095274/46878773-66a53080-ce44-11e8-9db1-d0daa3b3fc6e.png)

Also, if someone connects to the server it's immediately shuts down itself.

**Comment by xabier1989** [comment]
Follow the full guide, you need to fill the database credentials.
