### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by sriwanich** [xabier1989/WiredPlayers-RP#2]
![image](https://user-images.githubusercontent.com/10558483/36339429-0ae112ca-13f8-11e8-8906-631f7ac56b2f.png)

**Comment by xabier1989** [comment]
You're missing some required libraries, that should be copied into your **runtime/** folder. If you don´t want to search them, you can get them from this link:

[runtime.zip](https://github.com/xabier1989/WiredPlayers-RP/files/1733544/runtime.zip)

Also make sure you have the mod and bridge updated to its latest version, running updater.exe

**Comment by sriwanich** [comment]
Thank mate

**Comment by xabier1989** [comment]
Update your bridge version to the latest one using updater.exe

**Comment by sriwanich** [comment]
You Have Link Download Please Send to me

**Comment by sriwanich** [comment]
Server Okey But Register Server mate Charecter Not Spawn
![image](https://user-images.githubusercontent.com/10558483/36343983-3ec3e5ba-1446-11e8-84b4-9cbeb8b95381.png)

**Comment by xabier1989** [comment]
You need to insert a row into "accounts" table, with your social club username, a md5 hashed password and status set to 1

**Comment by sriwanich** [comment]
Thank mate. Do You Have ID Discord ?

**Comment by xabier1989** [comment]
Xabi#7963

**Comment by sriwanich** [comment]
Thank mate
