### ISSUE TITLE
New Markers and Item System?

### ISSUE THREAD

**Issue by ByteTV** [xabier1989/WiredPlayers-RP#21]
Sorry for bothering you again 🐙 
I wanted to ask how the item system works.
For example: when i create a new 24/7 how can the player buy items there?
My second question is: How/Where do you I create new Markers?

Sincerly 
Byte

**Comment by ByteTV** [comment]
*same with the barber/cloth shop, how do I open the buy-menu.  :)

**Comment by sing4pur** [comment]
Use command /purchase

**Comment by xabier1989** [comment]
About the markers, it is done for the first business of each type, if you want to add extra markers you can use API function for those new places.
