### ISSUE TITLE
Question about WP

### ISSUE THREAD

**Issue by RyUkApples** [xabier1989/WiredPlayers-RP#33]
Hey im new with Rage:MP (i was on FiveM before) and i learn the RAGE API etc.. And i want to know, to do an admin menu i need to do the server side in c#  and client side (open menu and other function) in js ? And same for a whitelist system ?

**Comment by AteshM** [comment]
For now, yes you have to do the clientside JS and the serverside C# but it also works JS, still JS is depreciated so you will have to learn C#. We dont know what to say the Whitelist System, check Rage Forum.
