### ISSUE TITLE
Car Color Problem

### ISSUE THREAD

**Issue by AteshM** [xabier1989/WiredPlayers-RP#34]
There is a problem about the /vehicle command so when you create a car it spawns it with only black color! Also when /vehicle modify color it's not chaning the color...

**Comment by joaodutra11** [comment]
Confirming this bug

**Comment by darnhold** [comment]
thats cause in the code (Admin.cs) is the Argument for the coloring not processed ... it spawns the cars with  hardcoded only Black (0,0,0 in both colors) cause the argument isn't passed to the create vehicle function.
