### ISSUE TITLE
Login Screen is not showing up

### ISSUE THREAD

**Issue by MrRoman2k4** [xabier1989/WiredPlayers-RP#39]
If i connect with the new build then my login screen isnt showing up and i dont have any errors.
I can connect to the server and everything is downloaded but then nothing.

**Comment by MrRoman2k4** [comment]
Okay so i found out now that i needed to update my game to the test version. but now if i join the Server he told me that he cant compile the clientside scripts and i got this error in the clientside_cs.txt 

https://pastebin.com/M7wPb0VZ

**Comment by xabier1989** [comment]
Yesterday an update was pushed on RAGE, so execute the updater.exe in order to get the latest version which fixes this issue.

**Comment by Noisereactz** [comment]
got the same problem.. anyone can help me?

**Comment by Kalle801** [comment]
hm. Same here since today
