### ISSUE TITLE
Can't use commands

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [xabier1989/WiredPlayers-RP#4]
Why? Chat hidden after type command and nothing do...

**Comment by xabier1989** [comment]
/help and /welcome commands are not finished yet, in case those are the commands you're testing.

**Comment by 15w34r0n3D4y** [comment]
You're right, i try other command and it works, thank you.

**Comment by xabier1989** [comment]
Now it shouldn't happen anymore, there was an issue making the server crash which was solved on the latest update from RAGE Multiplayer.
