### ISSUE TITLE
Does not start!

### ISSUE THREAD

**Issue by DarylDixonLS** [xabier1989/WiredPlayers-RP#45]
Have now eliminated all errors! Guilty, lay on me! Server starts without errors, but when connecting just nothing happens! see screen! https://www.bilder-upload.eu/upload/426d8f-1545058386.jpg

**Comment by DarylDixonLS** [comment]
Correction ;)
I have the Bootstrapper.dll replaced and now at least something works. I stand with a character now in the apartment. What else do I have to do? I can not find another mistake! https://www.bilder-upload.eu/upload/0a8c06-1545083068.jpg

**Comment by MrRoman2k4** [comment]
Do you have any errors in the Server-Console ?

It looks like that you dont have the c# client scripts enabled.

Go to your RageMP folder and create a text file with the name : enable-clientside-cs.txt and test it again.
