### ISSUE TITLE
Not possible To create character

### ISSUE THREAD

**Issue by buddyqc69** [xabier1989/WiredPlayers-RP#49]
I dont have problems with the console and log

**Comment by xabier1989** [comment]
What's the error then?

**Comment by buddyqc69** [comment]
Nothing error, im connect to the server at the lobby and have nothing is available, is not possible to go outside the lobby or create my character

I have respected the tutorial fully, is possible to verify the connexion of ragemp to server mysql?

**Comment by xabier1989** [comment]
Then you don't have client-side enabled, make sure you created that .txt file on the guide. If you did, it's an issue with RAGE.

**Comment by buddyqc69** [comment]
thats what i have in the exceptions file log

==================[05/02/2019 04:26:22 PM]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'WiredPlayers.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

**Comment by buddyqc69** [comment]
I need to create file on my client ragemp for that work?

**Comment by xabier1989** [comment]
Yes, it's on the guide.

**Comment by buddyqc69** [comment]
https://prnt.sc/mh6kvw the start of my console, i have create the file you have tell me and my character is bug on the same place if i check on the mirroir

**Comment by buddyqc69** [comment]
I need to inject to mysql accounts my info etc for be sure to connect to server without bug?

**Comment by buddyqc69** [comment]
im ont the motel, and if press F nothing appear

**Comment by xabier1989** [comment]
If the login doesn't work, nothing will work. As I said, if you created the file and still is not working, go and ask on RAGE discord, it's not related to the gamemode.

**Comment by buddyqc69** [comment]
need to connect with login and password before inside the server ?
