### ISSUE TITLE
login thing

### ISSUE THREAD

**Issue by hartturmch** [xabier1989/WiredPlayers-RP#5]
where did i change this login screen?
i want to not show login screen or change it... please? :)

**Comment by xabier1989** [comment]
It's called on **Login.cs** after the player connects to the server.

**Comment by sing4pur** [comment]
Hello, 
I would appreciate any help in solving the problem.
I would like to test gamemode, but I encountered a problem. I'm a little confused and I do not understand the most where I should be placing next : INSERT INTO accounts (socialName, password, status) VALUES ('YOUR_SOCIALCLUB_ACCOUNT', MD5('YOUR_DESIRED_PASSWORD'), 1); ?? Do you mean to edit in MySQL workbench your source wprp.sql file as with my credit... ??  Sorry, but I'm not a good programmer, but I'm trying to learn. I just want to mention that I do not have a social account. And I stuck in the room with a wrong password. Thank you.

**Comment by xabier1989** [comment]
After executing the wprp.sql script which creates all the tables, you have to open the database and insert a new row into 'accounts' table, filling the socialClub and password fields.

**Comment by sing4pur** [comment]
Database in root folder of gamemode wiredplayers? I do that but tnen when i connect to server ask me just for a password and when i typed its says wrong password?

**Comment by xabier1989** [comment]
With that query above, the password gets hashed to MD5, but you'll have to use the plain password to login into the server.

**Comment by sing4pur** [comment]
Thank you for the help I appreciate very much. I did not manage to connect to the server. In any case, I wish you all the best and in the future you will make even better progress :).

**Comment by sing4pur** [comment]
Login is fine. A have issue in my worckbench database in the client side. Now is fixed!
