### ISSUE TITLE
Tunning Menu bug

### ISSUE THREAD

**Issue by GermanY1337** [xabier1989/WiredPlayers-RP#56]
There is a bug with the Tunning Menu when its empty like there is no spoiler for a vehicle then you cant go back in the menu and the menu is still on your screen till you leave the game or restart the Server.

Screenshot : http://prntscr.com/muqgw8

**Comment by Dietergriffin** [comment]
@GermanY1337  habe mal eine frage 

kennst du dich mit dem projekt sehr gut aus hätten da ein paar fragen 


mit freundlichen grüßen 
Dietergriffin

**Comment by GermanY1337** [comment]
> @GermanY1337 habe mal eine frage
> 
> kennst du dich mit dem projekt sehr gut aus hätten da ein paar fragen
> 
> mit freundlichen grüßen
> Dietergriffin

ein bisschen ja was haste denn ?

**Comment by Dietergriffin** [comment]
bei uns ist das problem wenn man die datenbank einbindet ist das problem wenn man auf dem server möchte der server aus geht 

hätte sonst gefragt ob du vielleicht am weekend mal 1 stunde oder so zeit hätten wir das mal per ts3 reden können und du mal auf dem server gucken könntest wieso das problem ist 


habe schon sehr viel versucht aber bekommen es net hin 
hast du vielleicht steam sonst könnte ich dir da schreiben ??

vielen danke für deine antwort
mit freundlichen grüßen 

Dietergriffin

**Comment by GermanY1337** [comment]
https://steamcommunity.com/id/GermanY2k/
