### ISSUE TITLE
habe eine frage 

### ISSUE THREAD

**Issue by Dietergriffin** [xabier1989/WiredPlayers-RP#58]
hey ich wusste nicht wie ich dich das fragen kann des wegen musste ich es hier drüber machen 
wir haben euer projekt und wollte fragen ob wir das nutzen dürfen und später dann weiter entwickeln dürfen ??

und hätte noch eine frage ob man sich mal im ts3 treffen könnte weil wir habe paar kleine probleme vieleicht könnten sie uns dabei helfen 

hoffe sie können uns helfen 

mit freundlich grüßen 
dietergriffin

**Comment by xabier1989** [comment]
Could you remake your question in english, please? Don't understand german.

**Comment by Dietergriffin** [comment]
hey i did not know how to ask you this because i had to do it over here
we have your project and wanted to ask if we are allowed to use it and then develop it later?

and would have a question if you could meet in ts3 because we have a few small problems maybe you could help us

Hope you can help us

sincerely yours
dietergriffin

**Comment by xabier1989** [comment]
Sure, as long as you don't sell it, you're free to use as you want.

About the support, I have no time to join any voice server, that's why I'm using the forum on RAGE.

**Comment by Dietergriffin** [comment]
Thank you so much that we are allowed to use the project
