### ISSUE TITLE
Latest changes = No Login/Register/Start-spawn

### ISSUE THREAD

**Issue by Kalle801** [xabier1989/WiredPlayers-RP#69]
Good evening. Since today i dont get the login/register screen anymore and a new player do not spawn in the house, like always.

No matter what i do, i can not get it to work anymore.

**Comment by Kalle801** [comment]
For some reason i can only compile into: netcoreapp2.1  Version 2.2 is not available and i installed all versions of dotnet.

**Comment by Alaitocs** [comment]
Hola buenas descargue la ultima versión y efectivamente no funciona el registro, new player. 


Hello good download the latest version and the registry does not work, new player.
