### ISSUE TITLE
Missing WiredPlayers.dll

### ISSUE THREAD

**Issue by H4nSolo** [xabier1989/WiredPlayers-RP#7]
![ragemp_fehler2](https://user-images.githubusercontent.com/4975420/39993742-2d51c27e-5777-11e8-956c-8e2646da74b0.png)

Is this Importent?

**Comment by xabier1989** [comment]
Due to some changes, now it's mandatory to compile the gamemode before launching it. So just open the Visual Studio, compile the solution and that should fix the issue.

**Comment by xabier1989** [comment]
I will update it as soon as I fix and implement a few things that I have on my mind, sure. I uploaded this quick as one person didn't know how to make it work with the compiled .dll library.

**Comment by brunoscripter** [comment]
same here. 
Where is the gamemode to compile ? I have the same error.

**Comment by H4nSolo** [comment]
Please excuse my re-comment ;)
I think it is strongly appropriate here again to create a guide regarding the complication of the dll file.
I've tried several times today to import / compile the project in Visual Studio to get the DLL file out, which became a disaster for me.

**Comment by brunoscripter** [comment]
I couldn't compile, please help me.

**Comment by xabier1989** [comment]
I will add the compiling steps to the README, but I can't give additional support on how to do it if an error shows as that's Visual Studio related, nothing to do with the gamemode.
