### ISSUE TITLE
No Connection to the Server

### ISSUE THREAD

**Issue by freekie89** [xabier1989/WiredPlayers-RP#71]
Hey, i used the github version and when i start the server i become 2 issues in my server_exceptions

- [ ] 
- [ ] ==================[07.04.2019 19:01:05]==================
- [ ] System.IO.FileNotFoundException: Could not load the specified file.
- [ ] File name: 'WiredPlayers.resources'
- [ ]    at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
- [ ] =========================================================
- [ ] 
- [ ] ==================[07.04.2019 19:01:05]==================
- [ ] System.IO.FileNotFoundException: Could not load the specified file.
- [ ] File name: 'WiredPlayers.resources'
- [ ]    at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
- [ ] =========================================================

so and when i will join to the Server i become no Error he loaded the files from the Server and then nothing. No login no register no Hotel Room. I don't know why! Can you help me ?

**Comment by Kalle801** [comment]
Enevyone has this since some days ago. I also can not fix it.

**Comment by Alaitocs** [comment]
I'm the same

**Comment by xabier1989** [comment]
That error is common and won't stop the server from loading, as said on multiple issues. If it's not loading, you didn't create the required .txt file correctly.

**Comment by freekie89** [comment]
Yes, i have Create the .txt correct on my PC. But don‘t work :-(

**Comment by xabier1989** [comment]
Seems few users are having this problem and it's not related to the gamemode itself.
