### ISSUE TITLE
No aparece la interfaz de registro, login ni punto de respawn

### ISSUE THREAD

**Issue by birikos** [xabier1989/WiredPlayers-RP#72]
Hola Xabier, he seguido todos tus pasos para instalar el servidor y luego el gamemode.
Compilo wiredPlayers.csproj sin ningún problema y abro el servidor igual, y hasta ahí todo perfecto. El problema viene cuando cuando ya estoy dentro del servidor y todo cargado,
no me aparece el login ni tampoco el registro para poder crear mi cuenta de usuario. También cuando me desconecto, se me cierra auto el servidor dejándome este error en los logs:

> ==================[08/04/2019 17:23:45]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'WiredPlayers.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================
> ==================[08/04/2019 17:23:45]==================
System.IO.FileNotFoundException: Could not load file or assembly 'C:\RAGEMP\server-files\bridge\resources\WiredPlayers\bin\Debug\netcoreapp2.2\WiredPlayers.resources.dll'. El sistema no puede encontrar el archivo especificado.
File name: 'C:\RAGEMP\server-files\bridge\resources\WiredPlayers\bin\Debug\netcoreapp2.2\WiredPlayers.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)
   at Assembly System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(string assemblyPath)
=========================================================
> ==================[08/04/2019 17:24:10]==================
System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at object[] System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

Los dos primeros errores, según leí en otros problemas es habitual y no pasaría nada, pero el último no he visto nada...
En conclusión, ¿que podría tocar para que me apareciera el login y registro? ¿Qué debo hacer para quitar ese último error?

**Comment by xabier1989** [comment]
Parece que tienes el RAGE sin actualizar, ejecuta el updater.exe para que te descargue los últimos archivos.

**Comment by birikos** [comment]
> Parece que tienes el RAGE sin actualizar, ejecuta el updater.exe para que te descargue los últimos archivos.

He instalado de nuevo el juego y error persevera, no entiendo el por que.

Sobre que no se vea el login etc... de que puede ser?

**Comment by xabier1989** [comment]
Es de eso precisamente, no te logra arrancar el server.

**Comment by birikos** [comment]
Gracias por la contestación. Pude solucionar el problema.

**Comment by Kalle801** [comment]
> Es de eso precisamente, no te logra arrancar el server.

Maybe you should delete all files inside your "Client_resources" folder. You will see, that even for you the login wont be shown. I had the same, cause i still saw the login but my members dont. So i deleted my client_resources and....  No login anymore.

**Comment by Kalle801** [comment]
hmm. NVM it works.
