### ISSUE TITLE
Empty Gas = No Car stop

### ISSUE THREAD

**Issue by Kalle801** [xabier1989/WiredPlayers-RP#73]
I just noticed, that empty gas does not issue a car stop.
Regards.

**Comment by xabier1989** [comment]
Tested now and yes, the engine does stop.

**Comment by Kalle801** [comment]
Ill retest it.

Found another "bug". None of the Jobs shows: Waypoints/GPS and so on.

**Comment by xabier1989** [comment]
It shows a blip when you get into the vehicle, it's not supposed to create any waypoint.

**Comment by Kalle801** [comment]
oh lol. Thanks.

**Comment by Kalle801** [comment]
hm i gont get a blip. I created a faction for the delevery man and changed the faction of a card to it. I also accepted an order and had 400 seconds to deliver it but i get no blip.

**Comment by xabier1989** [comment]
You need to be on a vehicle, just read the code and make sure you'll checked how the things work, please. This tool is not for sending "how X works" questions, use the forum on RAGE for that.

**Comment by Kalle801** [comment]
Okay. Thank you ;)

**Comment by Kalle801** [comment]
Just to let you know. It now works and carstop on emty gas also works. Im new to this and already learn a damn lot cause of your amazing scripts.

Thanks you again. Ill post in the forums from now on.
