### ISSUE TITLE
Ammunation cant be use with any weapon

### ISSUE THREAD

**Issue by Kalle801** [xabier1989/WiredPlayers-RP#74]
Even if i own a weapon license.

**Comment by Kalle801** [comment]
+ Falling of from a driving motorcicle cause an extreme frame drop to ( 1 FPS)

**Comment by Kalle801** [comment]
+ dropping ammunition of the inventory = Server crash

**Comment by xabier1989** [comment]
All of this have been fixed

**Comment by Kalle801** [comment]
I can not write a pm to you in the fofum. I would like to support your work via Patron if you like.

**Comment by Kalle801** [comment]
+ Dropping ammo still crashes the server instantly.

**Comment by Kalle801** [comment]
+ Purchasing 2 masks and remove one (/complement mask remove) results in the first purchased mask, which is not removeable anymore. (No mask in use)
