### ISSUE TITLE
Missing some .dll while they are there

### ISSUE THREAD

**Issue by Redeye123** [xabier1989/WiredPlayers-RP#8]
![image](https://user-images.githubusercontent.com/828563/40047989-55aa3796-5831-11e8-9097-eb7357ad4f8a.png)

I get these warnings and they are in the runtime folder Am i doing something wrong or ? 

I even downloaded a runtime.zip from a previous question and pasted it in there and still it doesnt work

**Comment by xabier1989** [comment]
This issue is the same as yesterday, now rage needs a compiled gamemode so the meta.xml changed. 

Get the latest version here and compile the solution as stated in the updated README file.

**Comment by Redeye123** [comment]
Ah oke I downloaded a zip from the resources page from the rage.mp website 

Back to it BTW where do i need to put wiredplayers.dll just leave it there at bin/debug or copy it oper to runtime ?

**Comment by xabier1989** [comment]
Just leave it there, in the folder where it's generated.

**Comment by Redeye123** [comment]
Awesome thx for the help Keep up the awesome work !
