### ISSUE TITLE
Animations are not visible over the network (to other players).

### ISSUE THREAD

**Issue by Kalle801** [xabier1989/WiredPlayers-RP#80]
Please read the title ;)

**Comment by xabier1989** [comment]
It's RAGE issue, you'll have to set the loop flag to all the animations in order to sync them, which in some cases has no sense.

**Comment by Kalle801** [comment]
Okay thank you very much :)

**Comment by Kalle801** [comment]
+ as i can see: You already flagged a ton of animations with "loop" but even these are not "sync" over the network it seems.
