### ISSUE TITLE
Can't create Character (Menu doesn't show up)

### ISSUE THREAD

**Issue by Mxritzk** [xabier1989/WiredPlayers-RP#84]
After I join the server, nothing happens. There's no login screen or something like this. 

There is some text showing up at the pc but after I press F nothing happens (http://prntscr.com/ne66be).
I compiled the bridge. Do I also have to compile the clientside script?

**Comment by Kalle801** [comment]
You need a file called: "enalble-clientside-cs.txt".

**Comment by Mxritzk** [comment]
Where do I have to create the file and what has to be in it?

**Comment by Kalle801** [comment]
in the root folder of your ragemp

**Comment by Mxritzk** [comment]
In the root folder of the server? And what has to be in it?

**Comment by xabier1989** [comment]
In the root folder of the local PC of esch player, it has to be empty. All of this is told on the guide.
