### ISSUE TITLE
F key does not work

### ISSUE THREAD

**Issue by Ownness** [xabier1989/WiredPlayers-RP#88]
Hey. I need help. there are no problems with compiling and starting the server. I appear in the room, you must press "F", but nothing happens. File "enable-clientside-cs.txt" created at the root of the RAGEMP client.

 In the server_exceptions file.txt 
```
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'WiredPlayers.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
```
can you tell me where my mistake is?

in clientside_cs.txt
```
C#: compiling scripts..
```

**Comment by xabier1989** [comment]
Did a registration window show for you?

**Comment by Ownness** [comment]
hi. after your latest fix, registration windows dont't show

**Comment by xabier1989** [comment]
Do you have any error on console?

**Comment by Ownness** [comment]
there are no errors in the console

**Comment by xabier1989** [comment]
And does it show that "Can't connect" message?

**Comment by Ownness** [comment]
the character appears on the street
