### ISSUE TITLE
resources not being compiled

### ISSUE THREAD

**Issue by Ownness** [xabier1989/WiredPlayers-RP#89]
It's about the language resources not being compiled into .dll, so I'll just revert it when I have time. Meanwhile you can just use the previous version which has the same content.

are you fixed it?
I have the same error..how can I solve it?

**Comment by xabier1989** [comment]
You have to rename each .resx and remove the en-GB, as it doesn't correctly get the culture on .NET Core 2.0.7 (version on which the bridge is built)

**Comment by Ownness** [comment]
how exactly to rename?
