### ISSUE TITLE
Open project in visual studio

### ISSUE THREAD

**Issue by SkyBadPT** [xabier1989/WiredPlayers-RP#90]
Hello there, this is not a bug, but I didn't know any other way to open a question, I would like to know how can I open the project in visual studio in order to make some changes and add features, who know if I am able to do anything good that xavier likes and let me place it in the mod.
But I can't manage to open the entire project in Visual studio can someone guide me?

**Comment by Ownness** [comment]
> Hello there, this is not a bug, but I didn't know any other way to open a question, I would like to know how can I open the project in visual studio in order to make some changes and add features, who know if I am able to do anything good that xavier likes and let me place it in the mod.
> But I can't manage to open the entire project in Visual studio can someone guide me?

what exactly fails to open? open project file .sln

**Comment by xabier1989** [comment]
As it said @Ownness just open the .sln on Visual Studio and you're done.
