### ISSUE TITLE
Botón Comprar no aparece en catalogo

### ISSUE THREAD

**Issue by chopo156** [xabier1989/WiredPlayers-RP#91]
Buenas Xabi, abrir el catalogo y seleccionar un auto no aparece el boton de "comprar" edite el html en la linea 26 "button id="catalog-purchase" type="button" class=**btn btn-secondary hidden**" data-i18n="general.purchase" onclick="purchaseVehicle();"></button>"
por "button id="catalog-purchase" type="button" class=" **btn btn-secondary**" data-i18n="general.purchase" onclick="purchaseVehicle();"></button

no se si lo que hice cumple el propósito tuyo de comprar el auto, disculpa si no es asi, no hice un pullrequest porque no se si esta bien lo que hice, solo se que ahora aparece, abrazo!

**Comment by xabier1989** [comment]
No aparece porque no tienes dinero en el banco, está correcto como estaba.
