### ISSUE TITLE
business commands

### ISSUE THREAD

**Issue by Ownness** [xabier1989/WiredPlayers-RP#95]
business creation and modification commands do not work

**Comment by xabier1989** [comment]
You need to give yourself admin rank.

**Comment by Ownness** [comment]
my admin rank = 4

**Comment by chopo156** [comment]
What's command you use to create the business

**Comment by chopo156** [comment]
Try /negocio crear 1 in spanish

**Comment by Ownness** [comment]
> Try /negocio crear 1 in spanish

error. command not found. 
I localized English

**Comment by xabier1989** [comment]
The command now takes an extra parameter (interior/exterior on spanish, which would be inner/outer)

**Comment by Ownness** [comment]
> The command now takes an extra parameter (interior/exterior on spanish, which would be inner/outer)

did not understand, how is it now spelled correctly?
