### ISSUE TITLE
Cloth Shop

### ISSUE THREAD

**Issue by Fabown** [xabier1989/WiredPlayers-RP#98]
Cloth shop is broken since last update

**Comment by Ownness** [comment]
clothing store works

**Comment by Fabown** [comment]
Not Really :-) sometimes Menu Is empty sometimes it works

**Comment by xabier1989** [comment]
Make sure you have all the texts on statics/i18n/ folder.

**Comment by Fabown** [comment]
All the Textes are added correctly - Seems something is "Caching" things here - mby gta?

**Comment by xabier1989** [comment]
You can try deleting client_resources folder on RAGE's root folder, but also I added a new text for the clothes store only on the spanish file.

**Comment by Fabown** [comment]
Yea took this for the en.json allready and translated it and added it there - its weird
